### ISSUE TITLE
Toggle to exclude forked repos from list

### ISSUE THREAD

**Issue by bigpresh** [kritikaio/kritika.io#1]
```
10:40 <bigpresh> One little bit of feedback - when listing the user's repos to let them choose which ones to add, I 
                 think it'd be handy to have a toggle to exclude forks from the list (if GH's API tells you if a 
                 repo is a fork of another - I believe it does)
10:41 <bigpresh> e.g. I have plenty of repos that are just forked from someone else's where I've contributed 
                 something, but I generally wouldn't be interested in adding my fork of it to kritika.io
10:41 <vti> yes, that would be nice thing to add
```

**Comment by vti** [comment]
It should be done. I guess I shouldn't be the one closing issues :)

**Comment by bigpresh** [comment]
I don't see any reason you shouldn't close issues when you're happy they're dealt with - it's not like you need "signoff" or anything :)

It looks like it'll be much better with the "owner"/"forks"/"all" tabs - however, for me, all my repos (owned, and forked) appear on the owner tab, with nothing on the forks tab.

**Comment by bigpresh** [comment]
> however, for me, all my repos (owned, and forked) appear on the owner tab, with nothing on the forks tab.

Ah, ignore me, I hadn't clicked the "sync" button - once I did, it worked fine.  I imagine it was using a cached list that didn't have an "is a fork" flag stored, or something similar.
