### ISSUE TITLE
Make it clearer that analysis is not yet complete when a repo is added

### ISSUE THREAD

**Issue by bigpresh** [kritikaio/kritika.io#2]
```
10:45 <bigpresh> Also, when I add a repo, I get the first snapshot displayed, with "#1 ready" (which sounds like the 
                 analysis is done), but there are no violations shown, presumably as it hasn't actually been 
                 analysed at that point
10:45 <bigpresh> If I refresh, then I get them
10:45 <bigpresh> So it might be nice if the page you get after adding a repo is a "Please wait, fetching and 
                 analysing" (perhaps with some AJAXery to poll until results are available, then auto-refresh, for 
                 cuteness)
10:45 <vti> yeah, ready actually means "ready to be analyzed"
10:46 <vti> i will improve that
```

**Comment by vti** [comment]
I have added a rolling img to all the statuses except the finished ones. Does it make it clearer?

**Comment by bigpresh** [comment]
A bit clearer, yes, although personally I would replace the "This snapshot was analyzed automatically..." section (and the top violations/violators) with a paragraph making it clear it's not yet ready, e.g.:

> Hold tight, we're analyzing the first snapshot for you.  <Refresh the page> soon to see the results.

... or something along those lines.

I imagine what GitHub do when you fork a repository might be a good example to follow :)

**Comment by vti** [comment]
Ok... but I am not a web designer you know :D

**Comment by vti** [comment]
Take a look. It's epic :smile:
