### ISSUE TITLE
Installing GitHub webhook

### ISSUE THREAD

**Issue by kiwiroy** [kritikaio/kritika.io#8]
Under repository specific **Settings** -> **Integrations** -> **Incoming Webhooks**, toggling the install webhook for provider: GitHub, produces an *Internal Server Error*. Toggling *enable*/*disable* for the same provider toggles though.

**Comment by vti** [comment]
Thanks. I will take a look. That's probably because you didn't give admin permissions.

**Comment by kiwiroy** [comment]
Thanks, I now have, but still the same.
* webhooks write
* commit status yes
* orgs read yes
* private repos no

**Comment by kiwiroy** [comment]
I don't know if this helps but I enabled it manually, copying webhook details (replacing token) from another working repo and kritika.io now receives payloads correctly, but the toggle switch isn't correct. 
![screen shot 2017-11-24 at 1 20 11 pm](https://user-images.githubusercontent.com/313562/33191103-4b12217a-d11a-11e7-8b3b-14d603f0f57f.png)

**Comment by vti** [comment]
Can you explain how did you end up with this situation? Did you refresh the
token and then tried to reinstall?

**Comment by kiwiroy** [comment]
@vti I'm not entirely sure. I don't recall refreshing the token, the webhook was not installed the first time I looked at the settings page - when I was investigating why a `git push origin` wasn't updating the Kritika reporting. It might all be down to failing to login/signup on while on iOS. Apart from the toggle switch inconsistency in the image above everything is working in both the issue repository and the two others I have set up - which do not exhibit the issue.

**Comment by vti** [comment]
I will _try_ to fix it with weekend. Thanks again for the report! 👍

**Comment by vti** [comment]
This should be fixed.

**Comment by kiwiroy** [comment]
Appears to be. Thanks.
