### ISSUE TITLE
Private repos badges

### ISSUE THREAD

**Issue by kiwiroy** [kritikaio/kritika.io#9]
Is there a way to make this work?

Copying the markdown from `/users/<username>/repos/<id>/statuses` for `README.md` doesn't result in a badge being displayed on GitHub in private repos. Understandably the request needs to be authenticated, which isn't the case for [camo.githubusercontent.com](https://camo.githubusercontent.com/c1a2995bdf0ff04f7e4a51bebae678ec206dd30c/68747470733a2f2f6b726974696b612e696f2f75736572732f6b697769726f792f7265706f732f383935373431323231383035343037342f68656164732f6d61737465722f7374617475732e7376673f6272616e63683d6d6173746572) that caches (?) the badges.

**Comment by vti** [comment]
Yes, something like a security token limited only for this image could
work. Give me couple days :)

**Comment by vti** [comment]
This should be fixed and deployed.

**Comment by kiwiroy** [comment]
perfect!
